all:
	gcc -g -o sigmask_prt sigmask_prt.c   ../include/csapp.c -I ../include -lpthread
	gcc -g -o jmpmask jmpmask.c   ../include/csapp.c -I ../include -lpthread
	gcc -g -o sigsuspend sigsuspend.c   ../include/csapp.c -I ../include -lpthread
	gcc -g -o systemsign systemsign.c   ../include/csapp.c -I ../include -lpthread
	gcc -g -o sigtstp sigtstp.c   ../include/csapp.c -I ../include -lpthread
	