all:
	gcc -g -o getcopy getcopy.c ../include/ourhdr.c -I ../include
	gcc -g -o fgetscopy fgetscopy.c ../include/ourhdr.c -I ../include
	gcc -g -o stdiobufsiz stdiobufstatus.c ../include/ourhdr.c -I ../include
	gcc -g -o tmpfile tmpfile.c ../include/ourhdr.c -I ../include
