all:
	gcc -g -o gethole createmptyfile.c ../include/ourhdr.c -I ../include
	gcc -g -o lseekstdin lseekstdin.c ../include/ourhdr.c -I ../include
	gcc -g -o intout intout.c ../include/ourhdr.c -I ../include
	gcc -g -o access access.c ../include/ourhdr.c -I ../include
	gcc -g -o chmod chmod.c ../include/ourhdr.c -I ../include
	gcc -g -o fscount fscount.c ../include/ourhdr.c -I ../include
	gcc -g -o getfdauth getfdauth.c ../include/ourhdr.c -I ../include
	gcc -g -o statpr statpr.c ../include/ourhdr.c -I ../include
	gcc -g -o umask umask.c ../include/ourhdr.c -I ../include
	gcc -g -o unlink unlink.c ../include/ourhdr.c -I ../include
	gcc -g -o utime utime.c ../include/ourhdr.c -I ../include
