all:
	gcc -g -o isatty isatty.c   ../include/csapp.c -I ../include -lpthread
	gcc -g -o ttyname ttyname.c  ../include/csapp.c -I ../include -lpthread
	gcc -g -o cbreak cbreak.c  ../include/csapp.c -I ../include -lpthread
	gcc -g -o winszprt winszprt.c  ../include/csapp.c -I ../include -lpthread
	gcc -g -o getpass getpass.c  ../include/csapp.c -I ../include -lpthread
