all:
	gcc -g -o noblockwrt noblockwrt.c   ../include/csapp.c -I ../include -lpthread
	gcc -g -o lock lock.c   ../include/csapp.c -I ../include -lpthread
	gcc -g -o daemon daemon.c   ../include/csapp.c -I ../include -lpthread
	gcc -g -o mmap mmap.c   ../include/csapp.c -I ../include -lpthread
	gcc -g -o daemon_init daemon_init.c   ../include/csapp.c -I ../include -lpthread
	